### ISSUE TITLE
Incorrect signal information for aliased signal: BOARD_POWER

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#3231]
**Describe the bug**
I tried to use geopmread to display the signal information for BOARD_POWER and I expected to see the alias map to MSR::BOARD_POWER instead it maps to CNL::BOARD_POWER.

**GEOPM version**
v3.0.0

**Expected behavior**
```
[bgeltz@compute-node-1 ~]$ geopmread -i BOARD_POWER
BOARD_POWER:
    description: Power measured on the server's board.
    iogroup: MSR
    alias_for: MSR::BOARD_POWER
```

**Actual behavior**
```
[bgeltz@compute-node-1 ~]$ geopmread -i BOARD_POWER
BOARD_POWER:
    description: Power measured on the server's board.
    iogroup: CNL
    alias_for: CNL::BOARD_POWER
```

**Additional context**
I *think* this is happening because the CNL IOGroup is loaded after MSR (meaning it will be hit first when searching for signal information because we search in reverse plugin load order), and there's nothing in place to verify that the CNL IOGroup's signal is valid before returning the signal information.  In this case, the CNLIOGroup is not supported by the OS image, but the GEOPM service was compiled with support for the CNLIOGroup.

All aliased signals that are defined my multiple IOGroups should be examined to see if they also have this problem.

**Comment by bgeltz** [comment]
No longer an issue:
```
[bgeltz@node-1 ~]$ geopmread --version
geopmread 3.1.1.dev413+g53e2b3465

[bgeltz@node-1 ~]$ geopmread -i BOARD_POWER
BOARD_POWER:
    description: Average BOARD power over 40 ms or 8 control loop iterations
    alias_for: MSR::PLATFORM_ENERGY_STATUS:ENERGY rate of change
    alias_for: MSR::BOARD_POWER
    units: watts
    aggregation: expect_same
    domain: board
    iogroup: MSRIOGroup
```

Most likely fixed with #3660.
